// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoyageVoyage.Server.Data;

#nullable disable

namespace VoyageVoyage.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928120000_AddAnomalyAlerts")]
    partial class AddAnomalyAlerts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoyageVoyage.Server.Models.AnomalyAlert", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<string>("ExpenseId")
                    .HasColumnType("text");

                b.Property<string>("ReceiptId")
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<DateOnly>("TripEndDate")
                    .HasColumnType("date");

                b.Property<string>("TripId")
                    .HasColumnType("text");

                b.Property<DateOnly>("TripStartDate")
                    .HasColumnType("date");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("TripId");

                b.HasIndex("UserId");

                b.HasIndex("UserId", "Type", "TripId", "ExpenseId")
                    .IsUnique();

                b.ToTable("AnomalyAlerts");
            });

            modelBuilder.Entity("VoyageVoyage.Server.Models.BookingConfirmation", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("BlobName")
                    .HasColumnType("text");

                b.Property<string>("ContentType")
                    .HasColumnType("text");

                b.Property<string>("FileName")
                    .HasColumnType("text");

                b.Property<string>("ProviderName")
                    .HasColumnType("text");

                b.Property<string>("Reference")
                    .HasColumnType("text");

                b.Property<string>("TripId")
                    .HasColumnType("text");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<DateTimeOffset>("UploadedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("TripId");

                b.HasIndex("UserId");

                b.ToTable("BookingConfirmations");
            });

#pragma warning restore 612, 618
        }
    }
}
