// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoyageVoyage.Server.Data;

#nullable disable

namespace VoyageVoyage.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626084259_AddBookingConfirmations")]
    partial class AddBookingConfirmations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoyageVoyage.Server.Models.BookingConfirmation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingConfirmations");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.Expense", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.PersonalLeave", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalLeaves");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.PublicHoliday", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.Receipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LinkedEntityType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.SchoolHoliday", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolHolidays");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.TravelConstraints", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("AllowedDaysOfWeek")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("ConsiderPublicHolidays")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsiderVacationDays")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStrict")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxDaysPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PlanningHorizonDays")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("PublicHolidayRegions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("SchoolHolidayZones")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("TrainBookingThresholdDays")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TravelConstraints");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("VoyageVoyage.Server.Models.Trip", b =>
                {
                    b.OwnsOne("VoyageVoyage.Server.Models.HotelBooking", "HotelBooking", b1 =>
                        {
                            b1.Property<string>("TripId");

                            b1.Property<DateOnly>("BookingDate");

                            b1.Property<string>("HotelAddress")
                                .IsRequired();

                            b1.Property<string>("HotelName")
                                .IsRequired();

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("HotelBooking")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("VoyageVoyage.Server.Models.TrainBooking", "TrainBooking", b1 =>
                        {
                            b1.Property<string>("TripId");

                            b1.Property<string>("Arrival")
                                .IsRequired();

                            b1.Property<string>("Departure")
                                .IsRequired();

                            b1.Property<DateTimeOffset?>("DepartureDateTime");

                            b1.Property<DateTimeOffset?>("ReturnDateTime");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1
                                .ToJson("TrainBooking")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("HotelBooking");

                    b.Navigation("TrainBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
