using System.Text.Json.Serialization;

namespace VoyageVoyage.Server.Models;

/// <summary>
/// An alert generated by the anomaly detection workflow for a past trip.
/// Uniqueness is enforced on (user, type, trip, expense) to avoid duplicate alerts while conditions remain unchanged.
/// </summary>
public class AnomalyAlert
{
    public string Id { get; set; } = string.Empty;

    [JsonIgnore]
    public string UserId { get; set; } = string.Empty;

    public string TripId { get; set; } = string.Empty;

    public DateOnly TripStartDate { get; set; }

    public DateOnly TripEndDate { get; set; }

    public string? ExpenseId { get; set; }

    public string? ReceiptId { get; set; }

    public AlertType Type { get; set; }

    public string Description { get; set; } = string.Empty;

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    public AlertStatus Status { get; set; } = AlertStatus.New;
}
